### ISSUE TITLE
[Content Update] About Us

### ISSUE THREAD

**Issue by WanderZ** [NUSComputingDev/nuscomputing.com#139]
Could the about us page write up be updated to the following: 

The NUS Students’ Computing Club, commonly known as CompClub, is a constituent club under NUS Students' Union (NUSSU). It represents all the undergraduates in NUS School of Computing and works together with different organizations to cater to the members' different needs and wants. 
 CompClub strives to be the bridge between its members and the staff in the School of Computing, facilitating new initiatives by the school and channeling the feedback from its members to the right office. 

Members can share their feedback to us by sending it to connect@nuscomputing.com or message us at our Facebook page (fb.com/nuscomputing).

Throughout a typical academic year, CompClub organizes various events for its members. There are camps specially designed to assist the incoming freshmen, collaborations with the professors to provide addtional assistance to the weaker students, parties for our members who are graduating and many more events! Browse through the website for more information regarding our events and initiatives :)

**Comment by dev-nuscomputing** [comment]
Noted!

_Warmest Regards,_
_Nicholas Lum Aik Yong (Mr.)_
Director of Information Technology | 18th Management Committee
NUS Students' Computing Club

_m:_ (65) 90672038

_e: infotech@nuscomputing.com infotech@nuscomputing.com_

_w: nuscomputing.com http://nuscomputing.com/_

_f: fb.com/nuscomputing http://fb.com/nuscomputing_
_A Constituent Club of the NUS Students' Union_

School of Computing, Computing 1, 13 Computing Drive, S117417

Important: This email is confidential and may be privileged. If you are not
the intended recipient, please delete it and notify us immediately; you
should not copy or use it for any purpose, nor disclose its contents to any
other person. Thank you.

**Comment by kennho** [comment]
Done too. @WanderZ
