### ISSUE TITLE
[Student Portal | Lockers] Send an email to user of ballot when ballot has been edited

### ISSUE THREAD

**Issue by nicholaslum444** [NUSComputingDev/nuscomputing.com#170]
To catch accidental or malicious editing of ballot by other users.

Currently the current logged in user is emailed. This does not notify the user of the ballot in the event that the ballot edited does not belong to the current logged in user.

**Comment by unusep** [comment]
In what situation would the ballot be edited by someone other than the current logged in user?

**Comment by nicholaslum444** [comment]
@unusep malicious users might find a way to edit another user's ballot. it's simply a security precaution
