### ISSUE TITLE
Mobile view navbar menu dropdown pushes the pages downwards.

### ISSUE THREAD

**Issue by nicholaslum444** [NUSComputingDev/nuscomputing.com#18]
likely the javascript broke on the nav bar. find out why it broke and how to fix.

possible cause: the wrapping of the navbar in a row?

**Comment by jia1** [comment]
Good evening Nicholas,

Would like to confirm that the top bar came from
http://foundation.zurb.com/sites/docs/v/5.5.3/components/topbar.html
And it also pushes the page downwards.

**Comment by nicholaslum444** [comment]
ok cool, thanks!
