### ISSUE TITLE
need to crop and center the sponsor logos images

### ISSUE THREAD

**Issue by nicholaslum444** [NUSComputingDev/nuscomputing.com#49]
refer to image size on http://clubs.ntu.edu.sg/cec/?page_id=1930

**Comment by kennho** [comment]
hmm or I just follow the size i used in the mockup? which is fixed width of 150px. height according to the ratio

**Comment by nicholaslum444** [comment]
will it be too small? we can't use 5 in a row cos there are 12 columns, so we going with 4 in a row.

i guess u can experiment with the size. just replace one of the current images on the sponsor page (app/assets/images) to test

**Comment by kennho** [comment]
ohhh i seee. okays i try
